### ISSUE TITLE
Instructions on how to use

### ISSUE THREAD

**Issue by grav** [lambdaisland/cljbox2d#1]
Notes for others :)

- comment out the `lambdaisland/jbox2d-testbed-jogl` dependency in `deps.edn` (gave me a "Could not find artifact" error)
- run `clj -Adev` and then `(require 'cljbox2d.demo)` in the repl

**Comment by plexus** [comment]
Thanks @grav for trying it out! I did some cleanup, cut a proper release, and added better instructions to the README. Mind trying it out again?

Cheers!

**Comment by plexus** [comment]
We're two releases further down the road now, and there are instructions in the README for how to get started and how to run the demo. More improvements always welcome, meanwhile I think it's time to close this issue. Thank you for using cljbox2d!
